"""initial

Revision ID: 957121dd0594
Revises: 
Create Date: 2026-03-13 10:15:38.196696
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '957121dd0594'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('avg_brier_score', sa.Float(), nullable=True),
    sa.Column('total_predictions', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('feature_importance',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('feature_name', sa.String(length=200), nullable=False),
    sa.Column('feature_source', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('importance_score', sa.Float(), nullable=False),
    sa.Column('correlation_with_accuracy', sa.Float(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meta_agent_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('trigger', sa.String(length=50), nullable=False),
    sa.Column('input_summary', sa.Text(), nullable=True),
    sa.Column('output_summary', sa.Text(), nullable=False),
    sa.Column('actions_taken', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('scratchpad_entries_created', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meta_agent_runs_agent_type'), 'meta_agent_runs', ['agent_type'], unique=False)
    op.create_table('prediction_methods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('method_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('avg_accuracy', sa.Float(), nullable=True),
    sa.Column('best_categories', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('worst_categories', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('total_uses', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('scratchpads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scratchpads_agent_type'), 'scratchpads', ['agent_type'], unique=False)
    op.create_table('source_reliability',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('reliability_score', sa.Float(), nullable=False),
    sa.Column('accuracy_rate', sa.Float(), nullable=True),
    sa.Column('timeliness_score', sa.Float(), nullable=True),
    sa.Column('coverage_score', sa.Float(), nullable=True),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_reliability_platform'), 'source_reliability', ['platform'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('current_market_probability', sa.Float(), nullable=True),
    sa.Column('resolution_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_outcome', sa.String(length=50), nullable=True),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sources_category'), 'sources', ['category'], unique=False)
    op.create_index(op.f('ix_sources_external_id'), 'sources', ['external_id'], unique=False)
    op.create_index(op.f('ix_sources_platform'), 'sources', ['platform'], unique=False)
    op.create_table('user_interests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('notification_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_performance_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('brier_score', sa.Float(), nullable=False),
    sa.Column('calibration_error', sa.Float(), nullable=True),
    sa.Column('prediction_count', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('improvement_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('prediction_text', sa.Text(), nullable=False),
    sa.Column('predicted_outcome', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('time_horizon', sa.String(length=20), nullable=False),
    sa.Column('data_signals', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('prediction_id', sa.UUID(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_nodes_category'), 'event_nodes', ['category'], unique=False)
    op.create_table('prediction_scores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prediction_id', sa.UUID(), nullable=False),
    sa.Column('brier_score', sa.Float(), nullable=False),
    sa.Column('calibration_error', sa.Float(), nullable=True),
    sa.Column('absolute_error', sa.Float(), nullable=True),
    sa.Column('scored_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_node_id', sa.UUID(), nullable=False),
    sa.Column('target_node_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=30), nullable=False),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('detected_by', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_node_id'], ['event_nodes.id'], ),
    sa.ForeignKeyConstraint(['target_node_id'], ['event_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_edges')
    op.drop_table('prediction_scores')
    op.drop_index(op.f('ix_event_nodes_category'), table_name='event_nodes')
    op.drop_table('event_nodes')
    op.drop_table('predictions')
    op.drop_table('agent_performance_log')
    op.drop_table('user_interests')
    op.drop_index(op.f('ix_sources_platform'), table_name='sources')
    op.drop_index(op.f('ix_sources_external_id'), table_name='sources')
    op.drop_index(op.f('ix_sources_category'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_source_reliability_platform'), table_name='source_reliability')
    op.drop_table('source_reliability')
    op.drop_index(op.f('ix_scratchpads_agent_type'), table_name='scratchpads')
    op.drop_table('scratchpads')
    op.drop_table('prediction_methods')
    op.drop_index(op.f('ix_meta_agent_runs_agent_type'), table_name='meta_agent_runs')
    op.drop_table('meta_agent_runs')
    op.drop_table('feature_importance')
    op.drop_table('agents')
    # ### end Alembic commands ###
